import Link from "next/link";
import { ChevronLeft, ShieldCheck } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: "Privacy Policy | igquery.com",
  description: "Privacy policy for igquery.com - Instagram Search Query Optimizer.",
  alternates: {
    canonical: "https://www.igquery.com/privacy",
  },
};

export default function PrivacyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      
      <main className="flex-grow bg-zinc-50 dark:bg-zinc-950">
        <div className="container mx-auto max-w-3xl px-6 py-16">
          <Link 
            href="/" 
            className="mb-8 inline-flex items-center gap-2 text-sm font-medium text-zinc-500 hover:text-indigo-600 transition-colors"
          >
            <ChevronLeft className="h-4 w-4" />
            Back to Home
          </Link>

          <div className="rounded-3xl border border-zinc-200 bg-white p-8 shadow-sm dark:border-zinc-800 dark:bg-zinc-900 md:p-12">
            <div className="mb-10 flex items-center gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-50 dark:bg-indigo-900/20">
                <ShieldCheck className="h-6 w-6 text-indigo-600" />
              </div>
              <h1 className="text-3xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50">
                Privacy Policy
              </h1>
            </div>

            <article className="prose prose-zinc dark:prose-invert max-w-none space-y-6 text-zinc-600 dark:text-zinc-400">
              <p className="text-sm italic">Last updated: April 13, 2026</p>

              <p>
                At <strong>igquery.com</strong>, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our Instagram Search Query Optimizer.
              </p>

              <section className="space-y-4">
                <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100">1. Data Collection</h2>
                <p>
                  We believe in minimal data collection. We do not store your original seed keywords or the output queries generated by our tool in a persistent database.
                </p>
                <ul className="list-disc pl-5 space-y-1">
                  <li><strong>Queries:</strong> Processed in real-time and sent to third-party AI providers (AIML API/OpenAI) via secure encryption.</li>
                  <li><strong>Usage Data:</strong> We may collect anonymized traffic data to improve our service.</li>
                  <li><strong>Cookies:</strong> We use basic session cookies and local storage to maintain your preferences during your visit.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100">2. Third-Party Services</h2>
                <p>
                  To provide our services, we interact with the following third-party providers:
                </p>
                <ul className="list-disc pl-5 space-y-1">
                  <li><strong>AIML API/OpenAI:</strong> Used for generating search queries. Your input is shared with them solely for processing.</li>
                  <li><strong>Google reCAPTCHA:</strong> We use reCAPTCHA v3 to prevent spam and abuse. Use of reCAPTCHA is subject to the Google <Link href="https://policies.google.com/privacy" className="text-indigo-600 hover:underline">Privacy Policy</Link> and <Link href="https://policies.google.com/terms" className="text-indigo-600 hover:underline">Terms of Service</Link>.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100">3. Data Security</h2>
                <p>
                  We implement industry-standard security measures, including SSL (HTTPS) encryption, to protect your data during transit.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100">4. Changes to This Policy</h2>
                <p>
                  We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100">5. Contact Us</h2>
                <p>
                  If you have any questions about this Privacy Policy, please contact us at <strong>hi@igquery.com</strong> (placeholder).
                </p>
              </section>
            </article>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
